### PR TITLE
Add PickerView

### PR DESCRIPTION
**Pull request by filipealva**
## Summary:

Add [PickerView](http://github.com/filipealva/PickerView)

### CODE REVIEW

**Comment by filipealva** [comment]
@cjwirth hello man, there is something I can do to get this pull request reviewed? 

Thank you

**Comment by cjwirth** [comment]
Sorry, but just looking at the demo gif, it doesn't look to be significantly different than the default UIPickerView :/

**Comment by filipealva** [comment]
Its differential is to be highly customizable, but thanks for reviewing :D

**Comment by filipealva** [comment]
@cjwirth Hello :)

I've made some changes to PickerView. Now you can use a totally custom view as your PickerView item. 
Also added support to Objective-C.

Would be nice if you could take a look, if you search for "Custom UIPickerView" will see some people asking for a Picker with a totally custom view as item. 

No problems if it still "not awesome", hehe. 

https://github.com/filipealva/PickerView

**Pull request closed without merging**
