### PR TITLE
Add Adaptive Tab Bar

### PR DESCRIPTION
**Pull request by martinnormark**
[Adaptive Tab Bar](https://github.com/Ramotion/adaptive-tab-bar) removes label and increase icon size in tab bar, as time progress and you learn what the icons mean.

### CODE REVIEW

**Comment by cjwirth** [comment]
I like it, this library is pretty cool. Do you think you could maybe add/change the pictures so its more clear as to what it actually looks like? Right now the example just shows the icon.

Maybe I'll make one that I like when I get home tonight.

**Comment by martinnormark** [comment]
Sure. I'll try to mix something together. 

--
Martin H. Normark

**Comment by cjwirth** [comment]
Any updates on this? I'm thinking about giving this list a renewal, and it would be nice to add this.

**Comment by martinnormark** [comment]
Totally forgot about this one :neckbeard: 

How about using the images from the project readme: https://github.com/Ramotion/adaptive-tab-bar#tab-bar-after-install - perhaps crop them to the bottom part, showing the tab bar only?

**Comment by cjwirth** [comment]
Oh ok, those look pretty decent. I could probably put something together cutting off the bottom part, and having labels like "after 2 weeks" or whatever.

**Comment by cjwirth** [comment]
Took a while, but I finally put something together. :sun_with_face:

**Comment by martinnormark** [comment]
Cool!

**Pull request closed without merging**
