### PR TITLE
Add Notie

### PR DESCRIPTION
**Pull request by thii**

### CODE REVIEW

**Comment by cjwirth** [comment]
Hey, this is pretty nice. Would you mind resizing the image, and also placing a link in the actual NotificationsAlerts.md as well? Thanks

**Comment by thii** [comment]
What size should I resize the image to?

**Comment by cjwirth** [comment]
Maybe cut off the bottom half. 

The UI of the library is really only in the top, and there is a lot of unused space that isn't relevant

**Comment by thii** [comment]
Okay, I just fixed it.

**Comment by cjwirth** [comment]
:+1: Thanks!

**Pull request merged**
