### PR TITLE
Added Languages 

### PR DESCRIPTION
**Pull request by TolgaB**
I have added the languages (obj-c/swift) for the Animations section, I will add the rest later.

### CODE REVIEW

**Comment by cjwirth** [comment]
Thanks!

I think manually going through and adding this to each row will end up taking a lot of manual labor. It might be less effort for me to just update my scripts...

If you do still want to go through and do the whole thing -- I like the idea of having the name on the left, and the demo on the right. Appending a column on the right feels strange.

I was also considering just putting all the repo 'metadata' (name, stars, language, license) all in the left column, leaving more room for the demo column.

**Comment by TolgaB** [comment]
I've used most of these libraries so it wont take too much time. On the subject of the placement, I'll move it. Thanks for the response!

**Comment by smilinbob777** [comment]
Hey this is working out pretty good

**Comment by cjwirth** [comment]
Thanks for you work, but I got my scripts done :) 

I hope this new format is alright. Speaking of format, I'm going to use smaller, low-quality images for the main README.md, linking them to large versions (maybe have large ones in the individual pages as well). But thats a story for another ticket

**Pull request closed without merging**
